/**
 * Event handlers for Ligis CredentialRegistry on Monad Testnet.
 *
 * Types are generated by `envio codegen`. Until the first codegen run, this
 * file uses a loose shape so the package stays installable without a live
 * Envio login in CI.
 */
type Ctx = {
  CredentialIssued: { set: (row: Record<string, unknown>) => void };
  CredentialRevoked: { set: (row: Record<string, unknown>) => void };
  AgentCapabilityChanged: { set: (row: Record<string, unknown>) => void };
};

type Evt<P> = {
  params: P;
  logIndex: number;
  block: { number: number | bigint };
  transaction: { hash: string };
};

function rowId(
  block: number | bigint,
  logIndex: number,
  txHash: string,
): string {
  return `${block}-${logIndex}-${txHash}`;
}

export const CredentialRegistry = {
  CredentialIssued: {
    handler: async ({
      event,
      context,
    }: {
      event: Evt<{
        issuer: string;
        subject: string;
        capabilityHash: string;
        issuedAt: bigint | number;
        expiresAt: bigint | number;
        nonce: bigint | number;
      }>;
      context: Ctx;
    }) => {
      const id = rowId(
        event.block.number,
        event.logIndex,
        event.transaction.hash,
      );
      context.CredentialIssued.set({
        id,
        issuer: event.params.issuer.toLowerCase(),
        subject: event.params.subject.toLowerCase(),
        capabilityHash: event.params.capabilityHash.toLowerCase(),
        issuedAt: BigInt(event.params.issuedAt),
        expiresAt: BigInt(event.params.expiresAt),
        nonce: BigInt(event.params.nonce),
        blockNumber: BigInt(event.block.number),
        txHash: event.transaction.hash,
        logIndex: event.logIndex,
      });
    },
  },
  CredentialRevoked: {
    handler: async ({
      event,
      context,
    }: {
      event: Evt<{
        issuer: string;
        subject: string;
        capabilityHash: string;
        nonce: bigint | number;
        revokedAt: bigint | number;
      }>;
      context: Ctx;
    }) => {
      const id = rowId(
        event.block.number,
        event.logIndex,
        event.transaction.hash,
      );
      context.CredentialRevoked.set({
        id,
        issuer: event.params.issuer.toLowerCase(),
        subject: event.params.subject.toLowerCase(),
        capabilityHash: event.params.capabilityHash.toLowerCase(),
        nonce: BigInt(event.params.nonce),
        revokedAt: BigInt(event.params.revokedAt),
        blockNumber: BigInt(event.block.number),
        txHash: event.transaction.hash,
        logIndex: event.logIndex,
      });
    },
  },
  AgentCapabilityChanged: {
    handler: async ({
      event,
      context,
    }: {
      event: Evt<{
        subject: string;
        capabilityHash: string;
        capable: boolean;
      }>;
      context: Ctx;
    }) => {
      const id = rowId(
        event.block.number,
        event.logIndex,
        event.transaction.hash,
      );
      context.AgentCapabilityChanged.set({
        id,
        subject: event.params.subject.toLowerCase(),
        capabilityHash: event.params.capabilityHash.toLowerCase(),
        capable: event.params.capable,
        blockNumber: BigInt(event.block.number),
        txHash: event.transaction.hash,
        logIndex: event.logIndex,
      });
    },
  },
};
