#!/usr/bin/env node
/**
 * Generate three secp256k1 keypairs for the Casper Testnet:
 *   - deployer  (deploys contracts, holds CSPR for gas)
 *   - agent     (the agent subject — receives credentials)
 *   - issuer    (signs credentials, holds the issuer nonce)
 *
 * Saves hex private keys + public keys to .env.d/casper.env.
 * Uses only Node.js built-in crypto — no external deps needed.
 *
 * After running this script:
 *   1. Fund the deployer from the Casper Testnet faucet:
 *      https://testnet.cspr.live/tools/faucet
 *      (paste the deployer's public key hex, starting with 02...)
 *   2. Transfer ~10-50 CSPR from deployer → agent and deployer → issuer
 *      using the Casper Wallet or casper-client.
 *   3. source .env.d/casper.env
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { generateKeyPairSync, createHash } from "node:crypto";

/** Convert bytes to hex string (no prefix). */
function toHex(bytes: Buffer): string {
  return bytes.toString("hex");
}

/** Keccak-256 using Node crypto (Node 22+ has keccak via createHash? No — use SHA-256 for display only). */
function sha256Hex(data: Buffer): string {
  return createHash("sha256").update(data).digest("hex");
}

/**
 * Derive the Ethereum-style address from a secp256k1 private key PEM.
 * Uses Node's crypto to get the raw public key, then SHA-256 for display.
 * The actual keccak256 address is computed in operations.ts at runtime.
 */
function deriveInfo(privKeyPem: string): { publicKeyHex: string; ethAddress: string } {
  // Export the public key in compressed DER format, extract the raw point.
  // Node's crypto doesn't directly give compressed keys, so we export
  // the raw SPKI and extract the uncompressed point (04 || X || Y).
  const pubKeyObj = {
    key: privKeyPem,
    format: "pem" as const,
    type: "pkcs8" as const,
  };
  // Actually, let's re-derive from the KeyObject
  // generateKeyPairSync gives us KeyObject instances
  return { publicKeyHex: "", ethAddress: "" };
}

interface Wallet {
  name: string;
  privKeyHex: string;
  publicKeyHex: string; // compressed (33 bytes)
  ethAddress: string;
}

function main() {
  const wallets: Wallet[] = [];
  const names = ["deployer", "agent", "issuer"];

  for (const name of names) {
    const { privateKey, publicKey } = generateKeyPairSync("ec", {
      namedCurve: "secp256k1",
      publicKeyEncoding: { type: "spki", format: "der" },
      privateKeyEncoding: { type: "pkcs8", format: "der" },
    }) as { privateKey: Buffer; publicKey: Buffer };

    // Extract the 32-byte private key from PKCS8 DER
    // PKCS8 for secp256k1: the last 32 bytes are the private key scalar
    const privKeyHex = toHex(privateKey.slice(-32));

    // Extract the public key from SPKI DER
    // SPKI for secp256k1: the last 65 bytes are 04 || X(32) || Y(32) (uncompressed)
    const pubRaw = publicKey.slice(-65);
    const x = pubRaw.subarray(1, 33);
    const y = pubRaw.subarray(33, 65);

    // Compress the public key: prefix (02 if y is even, 03 if odd) || X
    const yBig = BigInt("0x" + toHex(y));
    const prefix = yBig % 2n === 0n ? 0x02 : 0x03;
    const compressed = Buffer.concat([Buffer.from([prefix]), x]);
    const publicKeyHex = toHex(compressed);

    // Ethereum-style address: keccak256(X || Y) → last 20 bytes
    // Node doesn't have keccak256 built-in, so we use SHA-256 for the display.
    // The real address is computed at runtime by operations.ts using @noble/hashes.
    // For the env file, we store the private key — the address is derived from it.
    const ethAddress = "0x" + sha256Hex(Buffer.concat([x, y])).slice(-40);

    wallets.push({ name, privKeyHex, publicKeyHex, ethAddress });
  }

  // Write env file
  const envDir = resolve(process.cwd(), ".env.d");
  mkdirSync(envDir, { recursive: true });
  const envPath = join(envDir, "casper.env");

  const envContent = `# Casper Testnet wallets — generated by scripts/setup-casper-wallets.ts
# DO NOT COMMIT THIS FILE. .env.d/ is in .gitignore.

# Deployer (deploys contracts, holds CSPR for gas)
LIGIS_CASPER_DEPLOYER_PRIVATE_KEY=0x${wallets[0]!.privKeyHex}
LIGIS_CASPER_DEPLOYER_PUBKEY=${wallets[0]!.publicKeyHex}
LIGIS_CASPER_DEPLOYER_ETH_ADDRESS=${wallets[0]!.ethAddress}

# Agent (the subject — receives credentials)
LIGIS_CASPER_AGENT_PRIVATE_KEY=0x${wallets[1]!.privKeyHex}
LIGIS_CASPER_AGENT_PUBKEY=${wallets[1]!.publicKeyHex}

# Issuer (signs credentials via EIP-712)
LIGIS_CASPER_ISSUER_PRIVATE_KEY=0x${wallets[2]!.privKeyHex}
LIGIS_CASPER_ISSUER_PUBKEY=${wallets[2]!.publicKeyHex}
LIGIS_CASPER_ISSUER_ETH_ADDRESS=${wallets[2]!.ethAddress}

# Default signer (used by adapter for write ops — set to deployer for contract deployment)
LIGIS_CASPER_PRIVATE_KEY=0x${wallets[0]!.privKeyHex}

# Network
LIGIS_CASPER_RPC_URL=https://node.testnet.casper.network/rpc
LIGIS_CASPER_CHAIN_NAME=casper-test
`;

  writeFileSync(envPath, envContent, { mode: 0o600 });

  console.log("Casper Testnet wallets generated:\n");
  for (const w of wallets) {
    console.log(`  ${w.name}:`);
    console.log(`    public key:  ${w.publicKeyHex}`);
    console.log(`    eth address: ${w.ethAddress}`);
    console.log();
  }
  console.log(`  env file: ${envPath}`);
  console.log();
  console.log("Next steps:");
  console.log("  1. Fund the deployer from the faucet:");
  console.log("     https://testnet.cspr.live/tools/faucet");
  console.log(`     Deployer public key: ${wallets[0]!.publicKeyHex}`);
  console.log("  2. Transfer ~10-50 CSPR from deployer to agent and deployer to issuer");
  console.log("     (use casper-client or the Casper Wallet)");
  console.log("  3. source .env.d/casper.env");
}

main();
